# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'QCPullRefresh' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QCPullRefresh
pod 'MJRefresh'
pod 'SVPullToRefresh'
pod 'CBStoreHouseRefreshControl'
pod 'YiRefresh'
end
